### PR TITLE
Extend try catch so app doesnt fall over on start

### PR DESCRIPTION
**Pull request by jonathan-fielding**
Hi

I found my app was falling over if no wiimote was connected because device is not defined, simply extended the try catch block to cover this use case and now works fine

Thanks

Jonathan

### CODE REVIEW

**Comment by andrew** [comment]
Great, thanks!

**Comment by s10wen** [comment]
@andrew wow, blast from the past 🚀🚀🚀 was good fun :)

**Comment by jonathan-fielding** [comment]
Am using this for a slide presenter tool I am building for a talk I am giving

**Comment by s10wen** [comment]
@jonathan-fielding nice job :+1:

**Pull request merged**
